import React from 'react'

const About = () => {
  return (
    <>
      <article className='about'>
        <h1>CookPal</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet neque non nisi blandit fermentum. Quisque ac lorem euismod, efficitur lorem ut, condimentum justo. Vivamus bibendum mi nec sapien vulputate, in luctus nulla sodales. Integer suscipit euismod libero, eu dapibus magna luctus id. Suspendisse ut nulla vel erat porta dictum. Donec non arcu sed sapien imperdiet tristique. Nulla ac sem metus. Vestibulum laoreet dui ac orci egestas, et tincidunt risus ullamcorper. Aenean eget lacus id libero ornare commodo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet magna at erat aliquet mattis. Sed bibendum ipsum non sem malesuada, vel luctus mi sollicitudin. Nulla facilisi. Fusce ornare magna nec neque finibus, id fermentum lectus fermentum. In eget nunc at velit ultricies porttitor. Ut vitae eros tristique, mattis est id, convallis lacus. Proin eget dolor sed eros elementum pretium. Nam consequat, sapien at malesuada vehicula, nulla justo fermentum dui, eget feugiat turpis ligula non orci. Sed porttitor varius ligula, non sagittis nibh.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet magna at erat aliquet mattis. Sed bibendum ipsum non sem malesuada, vel luctus mi sollicitudin. Nulla facilisi. Fusce ornare magna nec neque finibus, id fermentum lectus fermentum. In eget nunc at velit ultricies porttitor. Ut vitae eros tristique, mattis est id, convallis lacus. Proin eget dolor sed eros elementum pretium. Nam consequat, sapien at malesuada vehicula, nulla justo fermentum dui, eget feugiat turpis ligula non orci. Sed porttitor varius ligula, non sagittis nibh.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet magna at erat aliquet mattis. Sed bibendum ipsum non sem malesuada, vel luctus mi sollicitudin. Nulla facilisi. Fusce ornare magna nec neque finibus, id fermentum lectus fermentum. In eget nunc at velit ultricies porttitor. Ut vitae eros tristique, mattis est id, convallis lacus. Proin eget dolor sed eros elementum pretium. Nam consequat, sapien at malesuada vehicula, nulla justo fermentum dui, eget feugiat turpis ligula non orci. Sed porttitor varius ligula, non sagittis nibh.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet magna at erat aliquet mattis. Sed bibendum ipsum non sem malesuada, vel luctus mi sollicitudin. Nulla facilisi. Fusce ornare magna nec neque finibus, id fermentum lectus fermentum. In eget nunc at velit ultricies porttitor. Ut vitae eros tristique, mattis est id, convallis lacus. Proin eget dolor sed eros elementum pretium. Nam consequat, sapien at malesuada vehicula, nulla justo fermentum dui, eget feugiat turpis ligula non orci. Sed porttitor varius ligula, non sagittis nibh.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet magna at erat aliquet mattis. Sed bibendum ipsum non sem malesuada, vel luctus mi sollicitudin. Nulla facilisi. Fusce ornare magna nec neque finibus, id fermentum lectus fermentum. In eget nunc at velit ultricies porttitor. Ut vitae eros tristique, mattis est id, convallis lacus. Proin eget dolor sed eros elementum pretium. Nam consequat, sapien at malesuada vehicula, nulla justo fermentum dui, eget feugiat turpis ligula non orci. Sed porttitor varius ligula, non sagittis nibh.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet magna at erat aliquet mattis. Sed bibendum ipsum non sem malesuada, vel luctus mi sollicitudin. Nulla facilisi. Fusce ornare magna nec neque finibus, id fermentum lectus fermentum. In eget nunc at velit ultricies porttitor. Ut vitae eros tristique, mattis est id, convallis lacus. Proin eget dolor sed eros elementum pretium. Nam consequat, sapien at malesuada vehicula, nulla justo fermentum dui, eget feugiat turpis ligula non orci. Sed porttitor varius ligula, non sagittis nibh.</p>
      </article>
    </>
  )
}

export default About;
